version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    tty: true
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    hostname: pgadmin4
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin4_data:
